/**
 * Class-name merge utility.
 *
 * Re-exported rather than re-implemented so components can import `cn` from a
 * stable alias. The two available forms differ by import path, which also
 * marks component origin: `ui/` files generated by the shadcn CLI import `cn`
 * from `"cn"` directly, while Magic UI and hand-written files import from this
 * module.
 *
 * Usage: `cn("base-class", condition && "conditional", className)` — later
 * values win, conflicting Tailwind utilities resolve to the last one.
 */
export { cn } from "cn"
